[package]
name = "vislum-player"
version = "0.1.0"
edition = "2024"

[dependencies]
# vislum-asset = { path = "../vislum_asset" }
vislum-op = { path = "../vislum-op" }
serde_json = { workspace = true }
serde = { workspace = true }